### ISSUE TITLE
BigDecimal/DecimalFormat broken on (fixed) Java 8

### ISSUE THREAD

**Issue by fommil** [typelevel/scala#95] opened 2015-02-13 13:20 UTC
long story short, Java 7 had some broken `DecimalFormat.format` semantics which was fixed in Java 8, but it introduced another bug which is only fixed in 1.8.0_40-EA http://stackoverflow.com/a/23573248/1041691 https://github.com/PROSPricing/jdk8patch-halfupround/

You can see the new "correct" behaviour (which looks wrong) in this snippet:

``` scala
val f = new java.text.DecimalFormat("#,##0.000")
f.setRoundingMode(java.math.RoundingMode.HALF_UP)
f.format(1.2345) shouldEqual "1.234" // you probably expected "1.235"
```

The reason it fails is `1.2345` is not exactly representable as a `Double`, falling just below the halfway point, and nearest neighbour is `1.234`.

However, this **should** work, but doesn't in Scala 2.11.5:

``` scala
val f = new java.text.DecimalFormat("#,##0.000")
f.setRoundingMode(java.math.RoundingMode.HALF_UP)
f.format(BigDecimal("1.2345")) shouldEqual "1.235" // FAILS, gives "1.234"
```

workaround is to fall back to `java.math.BigDecimal`:

``` scala
val f = new java.text.DecimalFormat("#,##0.000")
f.setRoundingMode(java.math.RoundingMode.HALF_UP)
f.format(new java.math.BigDecimal("1.2345")) shouldEqual "1.235" // SUCCEEDS
```

Someone with visibility, please feel free to submit this to the upstream scala JIRA.

**Comment by fommil** [comment] 2015-11-11 19:08
@sethtisue was this ever flagged upstream? It keeps popping up recently, as we plan to upgrade to Java 8 at work.

**Comment by SethTisue** [comment] 2015-11-11 19:16
it doesn't look familiar, but that doesn't mean much; I don't pay special attention to BigDecimal

**Comment by fommil** [comment] 2015-11-11 19:20
Investment banks do.

**Comment by soc** [comment] 2015-12-23 00:56
I think @ichoran has a lot of experience with these parts of the code.

**Comment by Ichoran** [comment] 2015-12-23 01:22
I do.  The fix should be reasonably straightforward.  I can't upgrade to 1.8 u40, though, due to a bug in escape analysis that breaks some of my numeric code (u31 is the last good version).  Maybe I need to try u72; the fix wasn't in u66 (though I reported it and it was fixed in Java 9 at least, as far as I understood the issue tracker).  In any case, I'm not the right person to fix this since I can't conveniently test it on any of my machines.

**Comment by retronym** [comment] 2015-12-23 02:17
`java.text.DecimalFormat#format` internally type cases the `Object` typed argument, and dispatches to custom logic for `java.math.BigDecimal`.

``` java
// java/text/DecimalFormat.java
/**
     * Formats a number and appends the resulting text to the given string
     * buffer.
     * The number can be of any subclass of {@link java.lang.Number}.
     * <p>
     * This implementation uses the maximum precision permitted.
     * @param number     the number to format
     * @param toAppendTo the <code>StringBuffer</code> to which the formatted
     *                   text is to be appended
     * @param pos        On input: an alignment field, if desired.
     *                   On output: the offsets of the alignment field.
     * @return           the value passed in as <code>toAppendTo</code>
     * @exception        IllegalArgumentException if <code>number</code> is
     *                   null or not an instance of <code>Number</code>.
     * @exception        NullPointerException if <code>toAppendTo</code> or
     *                   <code>pos</code> is null
     * @exception        ArithmeticException if rounding is needed with rounding
     *                   mode being set to RoundingMode.UNNECESSARY
     * @see              java.text.FieldPosition
     */
    @Override
    public final StringBuffer format(Object number,
                                     StringBuffer toAppendTo,
                                     FieldPosition pos) {
        if (number instanceof Long || number instanceof Integer ||
                   number instanceof Short || number instanceof Byte ||
                   number instanceof AtomicInteger ||
                   number instanceof AtomicLong ||
                   (number instanceof BigInteger &&
                    ((BigInteger)number).bitLength () < 64)) {
            return format(((Number)number).longValue(), toAppendTo, pos);
        } else if (number instanceof BigDecimal) {
            return format((BigDecimal)number, toAppendTo, pos);
        } else if (number instanceof BigInteger) {
            return format((BigInteger)number, toAppendTo, pos);
        } else if (number instanceof Number) {
            return format(((Number)number).doubleValue(), toAppendTo, pos);
        } else {
            throw new IllegalArgumentException("Cannot format given Object as a Number");
        }
    }
```

`scala.math.BigDecimal` fall through to the case for `Number`, which converts it to a `Double` with `doubleValue`.

This is one of the reasons I dislike having wrapper classes in the Scala standard library (I voiced this objection in the recent discussion about the design of a Scala io library).

An alternative design might just use `java.lang.BigDecimal` as the type, and provide a `BigDecimalOps` implicit value class with extension methods. This probably isn't a drop in replacement for the current `scala.BigDecimal`.

**Comment by Ichoran** [comment] 2015-12-24 00:32
It's certainly not a drop-in replacement because Scala's BigDecimal carries along an associated MathContext, whereas the Java version requires you to specify it on each operation.  You would get many of the cases by having an implicit default MathContext, but the places where the behavior changes would only be found by wrong results being generated, which is really not a good way for numeric code to behave.

That said, this does make it nearly impossible to fix the bug directly.  If extension methods could be triggered to work when types of `Any` or `AnyRef` or `AnyVal` would otherwise be inferred, then you could just extend it to catch most cases.

However, I'm tempted to close this as "won't fix" because Java's behavior is pretty wonky.  `1.2345` prints as `1.2345`, but the half-up formatting prints as `1.234`.  Technically it's correct given the binary representation, except that "half up" is close to meaningless when you're dealing with the binary representation because you essentially never hit the halfway point.

**Comment by fommil** [comment] 2015-12-24 00:35
@Ichoran that behaviour is only when the number is coming in as `double`, and the rounding error is introduced at that point. When parsed from a `String` the scala version is clearly wrong.

**Comment by Ichoran** [comment] 2015-12-24 00:41
Sorta.  That's not the real bug.  Java's introduced a bug in its rounding algorithms by assuming the exact value is meaningful when it doesn't even make sense to think of it that way.

The real bug is this:

``` scala
scala> val f = new java.text.DecimalFormat("#,##0.000000000000000000000000000000000000000000000000000000000")
f: java.text.DecimalFormat = java.text.DecimalFormat@674dc

scala> val b = BigDecimal("0.92357491827589129451298478912748912749812749812748912798742984712991257198741289471")
b: scala.math.BigDecimal = 0.92357491827589129451298478912748912749812749812748912798742984712991257198741289471

scala> f.format(b)
res5: String = 0.923574918275891300000000000000000000000000000000000000000

scala> f.format(b.underlying)
res6: String = 0.923574918275891294512984789127489127498127498127489127987
```

That should be fixed, except there's no good way to do it.

**Comment by fommil** [comment] 2015-12-24 00:44
I disagree, I think the Java behaviour is now well defined... most people know that going from `double` => `BigDecimal` is error prone and the example above is a solid example of that which people who use big decimals can understand. The scala bug appears to be that a number starting out as an exact `String` is being coerced into a `double`, which is an epic fail. Frankly, until this is fixed, I couldn't possibly advise anybody to use scala's bigdecimals (I actively advise against it).

**Comment by Ichoran** [comment] 2015-12-24 00:44
As further evidence that the DecimalFormat is just broken (by design, due to a misunderstanding/disagreement of what rounding is for), look at `f.format(b)` above.  Note how it doesn't show the exact value of `b`, but rather the expansion of it to a sensible number of digits?

**Comment by fommil** [comment] 2015-12-24 00:46
I don't really see what your example is proving... you're showing that `DecimalFormat` is unable to render a scala `BigDecimal` (which has a broken constructor) to sufficient accuracy? This bug report is about the constructor of scala's `BigDecimal` coercing numbers through `double`, which is epically bad.

**Comment by Ichoran** [comment] 2015-12-24 00:50
@fommil - Did you read retronym's diagnosis?  The problem is Java casting within DecimalFormat.  (Plus the decision to allow an Object as an argument.)  It's not really fixable completely, since you can't dispatch based on the runtime type (even if you can have the compiler fix things it knows about).

So yes, if you want to use Java classes that use pattern matching on final Java classes, you can't use Scala classes instead.  That this is true of BigDecimal isn't terribly obvious, but we can fix the docs at least.

**Comment by Ichoran** [comment] 2015-12-24 00:51
@fommil - It has nothing to do with the `BigDecimal` constructor.

**Comment by fommil** [comment] 2015-12-24 00:52
@Ichoran yes, I understand, the Java standard library coerces the Scala `BigDecimal` into a `double` which basically destroys the whole point of it. Hence it should be removed from the standard library as soon as possible.

**Comment by fommil** [comment] 2015-12-24 00:53
(or the Scala implementation should extend from the Java class so that it pattern matches)

**Comment by Ichoran** [comment] 2015-12-24 00:53
In fact, unlike `java.math.BigDecimal`, Scala's BigDecimal goes out of its way to interpret `Double` values as if they are approximating decimal values, instead of assuming that you really really care about all those extra digits you get when taking the full binary expansion.

Also, I'd just ditch `DecimalFormat` first.  It's not treating numbers consistently.

But _certainly_ this shouldn't come as a surprise.  It is very surprising, and that is bad.

**Comment by fommil** [comment] 2015-12-24 00:54
:+1: totally agree with both of you, we should ditch it and go with `BigDecimalOps`.

**Comment by Ichoran** [comment] 2015-12-24 01:19
@fommil - Personally I think it's such a mess that one should ditch Java's BigDecimal also.  It throws exceptions at you for doing innocent things like 0.3 / 0.1 (if you forget it must be "0.3" / "0.1"), it blows your heap without warning on multiplication, it grinds to a dreadful halt if you try to get a hash code of a large number (try `java.math.BigDecimal.ONE.movePointRight(10000000).hashCode`!), its hash codes don't match `Double` even when representing the same number (not that Scala does either, but it could), and so on.

I'm not terribly motivated to do the work of BigDecimalOpsing it given what we're starting with.  Maybe someone else is, but I can think of a lot of better ways to spend one's time (even than to review the change, which would be a pretty severe breaking change given the loss of the `BigDecimal(x)` factory methods).

**Comment by fommil** [comment] 2015-12-24 01:28
Couldn't you just put methods in place that return the Java equivalents, with a type alias?

the Java versions are rock solid and ubiquitous in industry. Most people are fully aware not to use double in any step.

**Comment by Ichoran** [comment] 2015-12-24 01:55
@fommil - As long as you don't mind the use of namespace, yes, that's a possibility.

Yes, if you don't use big numbers, and you don't use double, and you always supply a MathContext that isn't UNLIMITED (or never divide and never multiply without a subsequent rounding step), and you expect trailing zeros to matter when you test for equality (including things like "0.05" multiply "0.04" not being "0.002") but to not matter when you use `compareTo`, and so on, then it is "rock solid".  That's a very brittle "rock".

And Scala has fixed a good portion of that stuff.  Some things will stay fixed with a sufficiently good PR; others will break.  I guess someone can try it and we can see whether we think it's worth it to be able to use `java.text.DecimalFormat`.

**Comment by soc** [comment] 2015-12-24 08:13
Maybe we could file a bug in Java, and make the case that the formatting should provide a hook for custom classes. I don't believe we are the only ones suffering from this.

**Comment by soc** [comment] 2015-12-24 08:15
(Apart from that, as we have a Scala implementation 90% available, it would be worthwhile to invest some thoughts into how a better BigInt/BigDecimal could look like.)

**Comment by fommil** [comment] 2015-12-24 08:27
@Ichoran I still don't see what the problem with the Java libraries is here. This is all a Scala wrapper problem. Direct use of the Java API doesn't do any of the rounding that you're suggesting.

**Comment by soc** [comment] 2015-12-24 10:48
From a Scala perspective, I'd like to have native variants, because we allow more library/language evolution, and I think it would be extremely interesting to turn BigInt/BigDecimal into value types as soon as the JVM ships support (plus we don't need to support all the legacy baggage/bug compatibility Java numbers have to support).

**Comment by Ichoran** [comment] 2015-12-26 22:27
@fommil - I am not sure you actually understand the quirks and limitations of Java `BigDecimal`.  Everything I have mentioned in the last couple of messages has been 100% Java.  Scala actually fixes some of the problems (e.g. with equality).  A wrapper only lets you fix some of the problems (e.g. equality cannot be fixed so that "0.05" \* "0.04" == "0.002").

Since we are not doing it from scratch, we have to take seriously the impact of replacing a working fairly-intuitive implementation with a more idiosyncratic one.

**Comment by fommil** [comment] 2015-12-26 22:59
@Ichoran all of your examples have been using scala's Ops around the `BigDecimal` so it's hard to know exactly what it is that you're showing. From what I understand from your examples, a lot of the problems you're demonstrating here are stemming from implicit `double => BigDecimal` construction, instead of `String => BigDecimal`. Can you write some of your complaints using the Java API rather than the scala wrapper?

**Comment by Ichoran** [comment] 2015-12-26 23:12
@fommil - I'm not writing Scala either, I'm writing an indication of what to do instead of all the necessary boilerplate.  But, okay, evaluate this (which should be valid in both Scala and Java):

``` java
(new java.math.BigDecimal("0.05")).multiply(new java.math.BigDecimal("0.04")).equals(new java.math.BigDecimal("0.002"))
```

I don't know about you, but my intuition is that the answer should be `true` given that we're doing exact decimal arithmetic.  [Wolfram Alpha seems to agree.](http://www.wolframalpha.com/input/?i=0.05+*+0.04+%3D%3D+0.002)

That the Java defaults make it especially dangerous to touch a `double` is bad, but by no means the only source of problems.

**Comment by fommil** [comment] 2015-12-26 23:35
@Ichoran that is certainly expected. The former has precision 2 and the latter has precision 1. This is critical to the use of the API and any attempt to hide it will only result in further confusions. I would recommend that if somebody does not fully grok precision, that they do not use `BigDecimal`. What you probably wanted to do was to strip the trailing zeros or set an explicit scale on your objects.

**Comment by Ichoran** [comment] 2015-12-27 01:32
@fommil - I understand why, given the implementation, that it happens.  I don't understand why you'd want it to.  It looks like an implementation detail leaking through into the API.  All it really gets you is "never use equals, always use `compareTo`".  And a bunch of confusion, since usually you can reason that if neither `a < b` nor `a == b` then `a > b`.  But not with `BigDecimal`!

I also don't understand why division throws an exception by default.  If you need a `MathContext` to make that a sane thing to do, maybe you shouldn't supply the method that looks like it might do something helpful but actually will blow up in your face?

And I don't understand why the default `hashCode` insists on explicitly representing something that is only indirectly represented (all the explicit zeros when you change decimal point position).  Again, if you want to represent truly big numbers, it's just a bomb lurking there.  There's no sensible reason for it except "Oops, we don't know how to make good hashes."

And I don't understand why "`double` is the Devil, never ever use it" is a sane choice of API.  If it's so dangerous to normal use, why provide easy methods to get yourself in trouble?  "Everyone knows not to do this obvious, apparently helpful thing" is a really poor argument for why an API is a good one.  I can agree that the flaws can, with training, be avoided.  That doesn't make them good.  It just drastically increases the cognitive burden for people doing what ought to be a simple task.

If someone wants to deal with every quirk of the Java BigDecimal API explicitly, they can of course just use Java BigDecimal and not use the Scala variants at all.  That Scala tries to make some things more sane (meaning: require less API-specific knowledge to avoid trouble) I don't think is a failing on Scala's part.  That it can't do it fully, and should have just given it up and not gotten into that area at all, maybe is.  But that ship's already sailed, and you haven't provided any compelling reasons why one _wants_ to have the Java behaviors.

Maybe we need more docs explaining how the Scala versions are more numerically sensible and safer at runtime, and where the wrapper causes incompatibilities with Java (e.g. `java.text.DecimalFormat`), with advice to call `underlying` if you need the underlying Java class.

**Comment by fommil** [comment] 2015-12-27 09:49
OK, well maybe that's a way forward for Scala, but perhaps best as a github project rather than something in the standard library. I, working in finance, will continue to use and recommend the Java version.

**Comment by markalanrichards** [comment] 2016-02-25 11:44
I found this problem too and raised this issue https://issues.scala-lang.org/browse/SI-9670 just found this github issue too :( maybe keep both open until this is fixed.

**Comment by fommil** [comment] 2016-02-25 11:48
@markalanrichards please create a link from there to here

**Comment by milessabin** [comment] 2016-08-12 14:39
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).

**Closed as completed** 2016-08-12 15:21 UTC
Labels: defunct
